### ISSUE TITLE
Getting ERR! enoent ENOENT: no such file or directory, chmod '/node_modules/sort-json/cmd.js'

### ISSUE THREAD

**Issue by ofershap** [ragingwind/gulp-chrome-manifest#14]
When trying to:
npm install --save gulp-chrome-manifest

im getting this error:
pm ERR! Linux 4.4.0-96-generic
npm ERR! argv "/usr/local/bin/node" "/usr/bin/npm" "install" "--save" "gulp-chrome-manifest"
npm ERR! node v8.4.0
npm ERR! npm  v3.10.10
npm ERR! path /data/projects/test/node_modules/sort-json/cmd.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod '/data/projects/test/node_modules/sort-json/cmd.js'
npm ERR! enoent ENOENT: no such file or directory, chmod '/data/projects/test/node_modules/sort-json/cmd.js'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /data/projects/test/npm-debug.log

**Comment by ofershap** [comment]
i found this: https://github.com/kesla/sort-json/issues/16 - it might help you solve the issue

**Comment by ragingwind** [comment]
as following error logs, sort-json has a problem about cmd.js.
