### ISSUE TITLE
Remove background completely for contentScript only app

### ISSUE THREAD

**Issue by oldergod** [ragingwind/gulp-chrome-manifest#7]
Is there a way to actually remove the background completely from the manifest?

In debug mode, I am using background only for debug purpose which I do not want to include into the finale manifest.json. Is it doable?

**Comment by ragingwind** [comment]
No, at this time, There is no way you can remove background. It will be added

**Comment by oldergod** [comment]
Are you already working on it? If no, I might find the time and send a PR.

**Comment by ragingwind** [comment]
Sure why not

**Comment by ragingwind** [comment]
7MCWP-XWUM6-EEJR
