### ISSUE TITLE
Disable concatenation

### ISSUE THREAD

**Issue by davisford** [ragingwind/gulp-chrome-manifest#9]
Hi, would you accept a PR to make concatenation optional?  I'm using babel with ES6 and doing [import / export modules](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import) and concatenating files won't work with ES6 modules, as a file represents a module.

**Comment by ragingwind** [comment]
I think that skipping concatenating is a just workaround for it. In this case, runnable scripts on chrome is prerequisite so you should do babel first and then using gulp-chrome-manifest

**Comment by davisford** [comment]
Well, there may be situations where I don't want to use babel.  I really wanted to avoid using babel, as Chrome supports most of ES6 now, but alas, modules are still one of the last features that aren't supported natively, so I am forced to babel-ify it.  Just a suggestion, though -- feel free to close, but if Chrome supported modules out of the box, I wouldn't want it concatenated, as it provides no additional value for a Chrome extension.

**Comment by ragingwind** [comment]
First of all, main feature of this generator is that concat/minify/uglify all of sources to make a production ready version. We could make each scripts built with only minify/uglify by --no-concat option but that is not my goal. All of sources should be tight after build. I think when Chrome supported modules, we can find out a new way of concatenating for module. or not we can keep discuss this.

**Comment by davisford** [comment]
@ragingwind i think this needs a little more thought.  when i build with babel, it converts es6 to es5, and since i am using es6 modules, i'm using the babel plugin:

``` json
// .babelrc
{
  "plugins": [
    "transform-es2015-modules-amd"
  ]
}
```

which transforms the module code in `define(...)` statements with require.js / AMD `require` statements.

but this pre-supposes I need `require.js` at runtime.  Normally, this would look like this in the Chrome manifest.json:

``` json
"background": {
   "scripts": [
      "require.js", "background.js"
   ]
}
```

This doesn't work with the plugin b/c it will embed require.js and concatenate it.  I can't concatenate it anyway the simple way the plugin does it anyway, b/c I need to run it through the `r.js` optimizer -- I can't just tack the files onto each other...order matters, and the require.js optimizer figures that out for me.

So, in order to make this work, I have to hack around a couple of things:

My manifest actually looks this before pre-processing with the plugin.  I actually have a LOT more source code -- many files actually, but I am just skipping / working around the plugin's concatenation and processing.  The sources are transformed through babel and dumped into `../build/scripts/`  

``` json
{
  "name": "__MSG_appName__",
  "version": "0.0.1",
  "manifest_version": 2,
  "description": "__MSG_appDescription__",
  "icons": {
    "16": "images/icon-16.png",
    "128": "images/icon-128.png"
  },
  "default_locale": "en",
  "background": {
    "scripts": [
      "../build/scripts/background.js"
    ]
  },
  "externally_connectable": {
    "matches": ["http://localhost:8000/*"]
  },
  "permissions": [
    "http://*/*",
    "https://*/*",
    "background"
  ]
}
```

Then I wrote a gulp task using gulp-requirejs-optimizer that takes the content of `../build/` and optimizes it for AMD and writes over `dist/background.js`  

Now, I have to write one more task that manually modifies `dist/manifest.json` and updates it from this:

``` json
    "background": {
        "scripts": [
            "background.js"
        ]
    },
```

to this:

``` json
    "background": {
        "scripts": [
            "require.js", "background.js"
        ]
    },
```

So, I'm just hacking around the plugin's handling of the scripts and concatenation anyway.  Would be nice to:

a) disable concatenation altogether since the current implementation of it is a bit naive and won't serve more advanced situations like AMD requirements 
b) even if one does end up using it, it is a bit of a pain to have to manually refer to all the files in the source -- would be much nicer to support glob patterns instead of having explicit paths for every file.

**Comment by ragingwind** [comment]
Supporting glob patterns would be great not only skipping concat but also `exclude` options can be removed in favour of using glob. FYI I have no opinion and willing about AMD. I never used before. 

UPDATED:
and more multi targets also should be supported with glob. It can be used for many cases.

```
'background': {
  'require.js': ['libs/**/*.js'],
  'background.js: ['scripts/**/*.js, !scripts/exclude.js'],
}
```

to be

```
'background': [
  'require.js', 'background.js'
]
```

**Comment by davisford** [comment]
incidentally, i'm ditching AMD in favor of webpack + commonjs with babel.  i just don't like requirejs very much, so my problem goes away.... but still, the process of concatenation, uglify, etc. and all that is much better farmed out to other tools, IMHO.  even with webpack, it has all its own suite of tools that analyze the dependencies, and optimize the final build file.  a simple file concatenation of a list of files in the order they appear on disk won't cut it.
